# Pandas Library
- http://pandas.pydata.org/pandas-docs/version/0.17.1/install.html
- You can find notes on the Pandas library at the link above.
- Using pandas 0.20.3 Python27

In [2]:
import csv
import numpy as np

## Import Pandas Library

In [3]:
import pandas as pd

## Read the data
- The data can be called 'Anything.csv'.  In this case it is under 'database.csv'.  We can assign a different variable name such as 'data'.

In [4]:
data = pd.read_csv('database.csv')

## Check the Data
- Next we want to check and make sure that the data is loaded.  We can just take a look at only a few rows and all the columns by using the below function.

In [5]:
data.head(20)

,Institution Name,Main Office,Branch Name,Branch Number,Established Date,Acquired Date,Street Address,City,County,State,Zipcode,Latitude,Longitude,2010 Deposits,2011 Deposits,2012 Deposits,2013 Deposits,2014 Deposits,2015 Deposits,2016 Deposits
0,JPMorgan Chase Bank,1,JPMorgan Chase Bank Main Office,0,01/01/1824,NaN,1111 Polaris Parkway,Columbus,Delaware,OH,43240,40.14453,-82.99115,633131000.0,743268000.0,832455000.0,916543000.0,1.032549e+09,1.069425e+09,1155185000
1,JPMorgan Chase Bank,0,Vernon Hills Scarsdale Branch,2,03/20/1961,NaN,676 White Plains Road,Scarsdale,Westchester,NY,10583,40.97008,-73.80670,293229.0,310791.0,325742.0,327930.0,3.277920e+05,3.414750e+05,381558
2,JPMorgan Chase Bank,0,Great Neck Northern Boulevard Branch,3,09/09/1963,NaN,410 Northern Boulevard,Great Neck,Nassau,NY,11021,40.77944,-73.72240,191011.0,206933.0,216439.0,237983.0,2.341830e+05,2.624550e+05,278940
3,JPMorgan Chase Bank,0,North Hartsdale Branch,4,02/19/1966,NaN,353 North Central Avenue,Hartsdale,Westchester,NY,10530,41.02654,-73.79168,87110.0,88367.0,93163.0,109659.0,1.119850e+05,1.167720e+05,140233
4,JPMorgan Chase Bank,0,Lawrence Rockaway Branch,5,01/16/1965,NaN,335 Rockaway Turnpike,Lawrence,Nassau,NY,11559,40.62715,-73.73675,172608.0,172749.0,189413.0,198445.0,2.051980e+05,2.232000e+05,235594
5,JPMorgan Chase Bank,0,Mount Vernon Branch,9,02/25/1964,NaN,22 West First Street,Mount Vernon,Westchester,NY,10550,40.91144,-73.83804,146820.0,136672.0,140678.0,154313.0,1.487070e+05,1.454990e+05,151949
6,JPMorgan Chase Bank,0,Castle Hill Branch,12,12/11/1965,NaN,784 Castle Hill Avenue,Bronx,Bronx,NY,10473,40.82292,-73.84887,75131.0,80172.0,82333.0,94538.0,9.704600e+04,1.071660e+05,110592
7,JPMorgan Chase Bank,0,Burnside Avenue Branch,15,02/14/1922,NaN,5 West Burnside Avenue,Bronx,Bronx,NY,10453,40.85389,-73.90760,39888.0,42546.0,43800.0,45867.0,5.136300e+04,5.669300e+04,62993
8,JPMorgan Chase Bank,0,Gun Hill Branch,16,12/18/1950,NaN,1308 East Gun Hill Road,Bronx,Bronx,NY,10469,40.87151,-73.84823,73702.0,70049.0,70447.0,78946.0,8.067700e+04,8.275600e+04,88954
9,JPMorgan Chase Bank,0,Kingsbridge Road Branch,18,08/18/1924,NaN,66 East Kingsbridge Road,Bronx,Bronx,NY,10468,40.86671,-73.89562,69778.0,72816.0,74729.0,75470.0,7.875900e+04,8.397800e+04,88674
10,JPMorgan Chase Bank,0,Riverdale Branch,20,06/01/1950,NaN,3775 Riverdale Avenue,Bronx,Bronx,NY,10463,40.88763,-73.90737,304300.0,311508.0,330224.0,360791.0,3.672020e+05,3.644350e+05,387333
11,JPMorgan Chase Bank,0,Washington Heights Branch,21,01/02/1909,NaN,1421 Saint Nicholas Avenue,New York City,New York,NY,10033,40.84941,-73.93370,136997.0,142882.0,151420.0,158669.0,1.578620e+05,1.633360e+05,179566
12,JPMorgan Chase Bank,0,Broadway Branch,22,07/12/1926,NaN,5581 Broadway,Bronx,Bronx,NY,10463,40.87913,-73.90465,113665.0,112165.0,122634.0,126619.0,1.240310e+05,1.344750e+05,131545
13,JPMorgan Chase Bank,0,Westchester Square Branch,24,06/29/1959,NaN,2725 East Tremont Avenue,Bronx,Bronx,NY,10461,40.84239,-73.84501,155289.0,157396.0,161177.0,169839.0,1.674950e+05,1.835440e+05,194609
14,JPMorgan Chase Bank,0,Bay Parkway and 85th St Branch,26,03/25/1964,NaN,8418 Bay Parkway,Brooklyn,Kings,NY,11214,40.60268,-73.99304,187794.0,195965.0,214398.0,227519.0,2.521240e+05,2.785470e+05,297821
15,JPMorgan Chase Bank,0,Grand Army Plaza Branch,33,03/14/1927,NaN,401 Flatbush Avenue,Brooklyn,Kings,NY,11238,40.67576,-73.97135,135506.0,136764.0,146051.0,163797.0,1.780010e+05,2.276470e+05,255084
16,JPMorgan Chase Bank,0,Carroll Gardens Branch,34,06/09/1913,NaN,79 Hamilton Avenue,Brooklyn,Kings,NY,11231,40.68279,-74.00556,46199.0,51254.0,54859.0,70898.0,6.982400e+04,7.753600e+04,79441
17,JPMorgan Chase Bank,0,Third Avenue & 51st Street Branch,37,05/05/1961,NaN,850 Third Avenue,New York City,New York,NY,10022,40.75675,-73.97008,463550.0,456859.0,508804.0,540179.0,5.957860e+05,5.817250e+05,643283
18,JPMorgan Chase Bank,0,East End Branch,38,05/22/1961,NaN,1495 York Avenue,New York City,New York,NY,10075,40.77158,-73.95038,299301.0,306225.0,317068.0,359173.0,4.107370e+05,4.251690e+05,447613
19,JPMorgan Chase Bank,0,Audubon Branch,40,04/02/1917,NaN,3940 Broadway,New York City,New York,NY,10032,40.83951,-73.94077,91380.0,97219.0,104093.0,106875.0,1.142920e+05,1.222200e+05,139830

- We can also check the end/tail of the data which in this case is the last five rows as shown below:

In [6]:
data.tail()

,Institution Name,Main Office,Branch Name,Branch Number,Established Date,Acquired Date,Street Address,City,County,State,Zipcode,Latitude,Longitude,2010 Deposits,2011 Deposits,2012 Deposits,2013 Deposits,2014 Deposits,2015 Deposits,2016 Deposits
5408,JPMorgan Chase Bank,0,Alameda and Compton Blvd Branch,7981,11/03/2015,NaN,251 E Compton Blvd,Compton,Los Angeles,CA,90220,33.89601,-118.22084,NaN,NaN,NaN,NaN,NaN,NaN,3446
5409,JPMorgan Chase Bank,0,Charleston and Rancho,7982,02/02/2016,NaN,2311 W Chafrleston Blvd,Las Vegas,Clark,NV,89102,36.14270,-115.19043,NaN,NaN,NaN,NaN,NaN,NaN,2666
5410,JPMorgan Chase Bank,0,Los Olivos Branch,7984,03/15/2016,NaN,8593 Irvine Center Drive,Irvine,Orange,CA,92618,33.64412,-117.74453,NaN,NaN,NaN,NaN,NaN,NaN,6689
5411,JPMorgan Chase Bank,0,Lake Forest Branch,7988,01/01/2016,NaN,5660 Read Blvd,New Orleans,Orleans,LA,70127,30.03205,-89.97260,NaN,NaN,NaN,NaN,NaN,NaN,94133
5412,JPMorgan Chase Bank,0,Buffalo-Mm Branch,7989,01/01/2016,NaN,350 Main Street,Buffalo,Erie,NY,14202,42.88429,-78.87487,NaN,NaN,NaN,NaN,NaN,NaN,45596

## Dimensions
- In order to create an idea it is better to check how many rows and columns the data has.  The first number is for the rows and the second if for the columns.

In [7]:
data.shape

(5413, 20)

## Check the Type of the Data

In [8]:
type(data)

pandas.core.frame.DataFrame

## Set Index
- Column named 'State' is set as the index column.

In [9]:
df1 = data.set_index('State')

df1

,Institution Name,Main Office,Branch Name,Branch Number,Established Date,Acquired Date,Street Address,City,County,Zipcode,Latitude,Longitude,2010 Deposits,2011 Deposits,2012 Deposits,2013 Deposits,2014 Deposits,2015 Deposits,2016 Deposits
State,,,,,,,,,,,,,,,,,,,
OH,JPMorgan Chase Bank,1,JPMorgan Chase Bank Main Office,0,01/01/1824,NaN,1111 Polaris Parkway,Columbus,Delaware,43240,40.14453,-82.99115,633131000.0,743268000.0,832455000.0,916543000.0,1.032549e+09,1.069425e+09,1155185000
NY,JPMorgan Chase Bank,0,Vernon Hills Scarsdale Branch,2,03/20/1961,NaN,676 White Plains Road,Scarsdale,Westchester,10583,40.97008,-73.80670,293229.0,310791.0,325742.0,327930.0,3.277920e+05,3.414750e+05,381558
NY,JPMorgan Chase Bank,0,Great Neck Northern Boulevard Branch,3,09/09/1963,NaN,410 Northern Boulevard,Great Neck,Nassau,11021,40.77944,-73.72240,191011.0,206933.0,216439.0,237983.0,2.341830e+05,2.624550e+05,278940
NY,JPMorgan Chase Bank,0,North Hartsdale Branch,4,02/19/1966,NaN,353 North Central Avenue,Hartsdale,Westchester,10530,41.02654,-73.79168,87110.0,88367.0,93163.0,109659.0,1.119850e+05,1.167720e+05,140233
NY,JPMorgan Chase Bank,0,Lawrence Rockaway Branch,5,01/16/1965,NaN,335 Rockaway Turnpike,Lawrence,Nassau,11559,40.62715,-73.73675,172608.0,172749.0,189413.0,198445.0,2.051980e+05,2.232000e+05,235594
NY,JPMorgan Chase Bank,0,Mount Vernon Branch,9,02/25/1964,NaN,22 West First Street,Mount Vernon,Westchester,10550,40.91144,-73.83804,146820.0,136672.0,140678.0,154313.0,1.487070e+05,1.454990e+05,151949
NY,JPMorgan Chase Bank,0,Castle Hill Branch,12,12/11/1965,NaN,784 Castle Hill Avenue,Bronx,Bronx,10473,40.82292,-73.84887,75131.0,80172.0,82333.0,94538.0,9.704600e+04,1.071660e+05,110592
NY,JPMorgan Chase Bank,0,Burnside Avenue Branch,15,02/14/1922,NaN,5 West Burnside Avenue,Bronx,Bronx,10453,40.85389,-73.90760,39888.0,42546.0,43800.0,45867.0,5.136300e+04,5.669300e+04,62993
NY,JPMorgan Chase Bank,0,Gun Hill Branch,16,12/18/1950,NaN,1308 East Gun Hill Road,Bronx,Bronx,10469,40.87151,-73.84823,73702.0,70049.0,70447.0,78946.0,8.067700e+04,8.275600e+04,88954
NY,JPMorgan Chase Bank,0,Kingsbridge Road Branch,18,08/18/1924,NaN,66 East Kingsbridge Road,Bronx,Bronx,10468,40.86671,-73.89562,69778.0,72816.0,74729.0,75470.0,7.875900e+04,8.397800e+04,88674
NY,JPMorgan Chase Bank,0,Riverdale Branch,20,06/01/1950,NaN,3775 Riverdale Avenue,Bronx,Bronx,10463,40.88763,-73.90737,304300.0,311508.0,330224.0,360791.0,3.672020e+05,3.644350e+05,387333
NY,JPMorgan Chase Bank,0,Washington Heights Branch,21,01/02/1909,NaN,1421 Saint Nicholas Avenue,New York City,New York,10033,40.84941,-73.93370,136997.0,142882.0,151420.0,158669.0,1.578620e+05,1.633360e+05,179566
NY,JPMorgan Chase Bank,0,Broadway Branch,22,07/12/1926,NaN,5581 Broadway,Bronx,Bronx,10463,40.87913,-73.90465,113665.0,112165.0,122634.0,126619.0,1.240310e+05,1.344750e+05,131545
NY,JPMorgan Chase Bank,0,Westchester Square Branch,24,06/29/1959,NaN,2725 East Tremont Avenue,Bronx,Bronx,10461,40.84239,-73.84501,155289.0,157396.0,161177.0,169839.0,1.674950e+05,1.835440e+05,194609
NY,JPMorgan Chase Bank,0,Bay Parkway and 85th St Branch,26,03/25/1964,NaN,8418 Bay Parkway,Brooklyn,Kings,11214,40.60268,-73.99304,187794.0,195965.0,214398.0,227519.0,2.521240e+05,2.785470e+05,297821
NY,JPMorgan Chase Bank,0,Grand Army Plaza Branch,33,03/14/1927,NaN,401 Flatbush Avenue,Brooklyn,Kings,11238,40.67576,-73.97135,135506.0,136764.0,146051.0,163797.0,1.780010e+05,2.276470e+05,255084
NY,JPMorgan Chase Bank,0,Carroll Gardens Branch,34,06/09/1913,NaN,79 Hamilton Avenue,Brooklyn,Kings,11231,40.68279,-74.00556,46199.0,51254.0,54859.0,70898.0,6.982400e+04,7.753600e+04,79441
NY,JPMorgan Chase Bank,0,Third Avenue & 51st Street Branch,37,05/05/1961,NaN,850 Third Avenue,New York City,New York,10022,40.75675,-73.97008,463550.0,456859.0,508804.0,540179.0,5.957860e+05,5.817250e+05,643283
NY,JPMorgan Chase Bank,0,East End Branch,38,05/22/1961,NaN,1495 York Avenue,New York City,New York,10075,40.77158,-73.95038,299301.0,306225.0,317068.0,359173.0,4.107370e+05,4.251690e+05,447613
NY,JPMorgan Chase Bank,0,Audubon Branch,40,04/02/1917,NaN,3940 Broadway,New York City,New York,10032,40.83951,-73.94077,91380.0,97219.0,104093.0,106875.0,1.142920e+05,1.222200e+05,139830
NY,JPMorgan Chase Bank,0,First Avenue & 72nd Street Branch,41,06/15/1964,NaN,360 East 72nd Street,New York City,New York,10021,40.76815,-73.95696,384454.0,364852.0,387515.0,440753.0,5.005740e+05,4.838350e+05,536219
NY,JPMorgan Chase Bank,0,Soho Branch,42,10/18/1954,NaN,525 Broadway,New York City,New York,10012,40.72290,-73.99889,286082.0,320252.0,344141.0,385854.0,4.888860e+05,5.081220e+05,615029
NY,JPMorgan Chase Bank,0,Times Square Branch,44,05/02/1927,NaN,3 Times Square,New York City,New York,10036,40.75658,-73.98629,313024.0,338725.0,432032.0,449569.0,4.740470e+05,4.959290e+05,532606
NY,JPMorgan Chase Bank,0,Broadway Lispenard Branch,45,08/01/1922,NaN,407 Broadway,New York City,New York,10013,40.72258,-74.00624,150592.0,160595.0,204645.0,244811.0,2.757260e+05,3.069020e+05,333954
NY,JPMorgan Chase Bank,0,Chinatown Branch,46,11/24/1919,NaN,180 Canal Street,New York City,New York,10013,40.71668,-73.99770,480964.0,523824.0,589914.0,638030.0,7.156070e+05,7.914130e+05,892267
NY,JPMorgan Chase Bank,0,Yorkville Branch,52,06/15/1914,NaN,126 East 86th Street,New York City,New York,10028,40.77966,-73.95609,383871.0,410662.0,437302.0,490441.0,5.388600e+05,5.265580e+05,535283
NY,JPMorgan Chase Bank,0,Columbus Avenue & 72nd Street Branch,62,10/18/1954,NaN,260 Columbus Avenue,New York City,New York,10023,40.77746,-73.97885,311593.0,350759.0,338917.0,356374.0,3.843710e+05,3.830140e+05,429310
NY,JPMorgan Chase Bank,0,Bloomingdales Branch,63,08/02/1915,NaN,770 Lexington Avenue,New York City,New York,10065,40.76302,-73.96761,273852.0,284524.0,295659.0,301179.0,3.650230e+05,3.569220e+05,353925
NY,JPMorgan Chase Bank,0,London Terrace Branch,64,05/01/1931,NaN,475 West 23rd Street,New York City,New York,10011,40.74743,-74.00339,143289.0,163960.0,168332.0,194739.0,2.245360e+05,2.455730e+05,249426
NY,JPMorgan Chase Bank,0,Tremont Branch,71,10/18/1954,NaN,601 East Tremont Avenue,Bronx,Bronx,10457,40.84628,-73.89296,48180.0,43965.0,45267.0,48717.0,5.394900e+04,5.609300e+04,56539
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
FL,JPMorgan Chase Bank,0,Polo Club Shoppes Branch,7952,06/02/2015,NaN,17955 South Military Trail,Boca Raton,Palm Beach,33496,26.40962,-80.12185,NaN,NaN,NaN,NaN,NaN,1.470000e+03,19184
CA,JPMorgan Chase Bank,0,Brookhurst and Mcfadden Branch,7953,07/07/2015,NaN,15512 Brrokhurst Street,Westminster,Orange,92683,33.73733,-117.95465,NaN,NaN,NaN,NaN,NaN,NaN,24401
FL,JPMorgan Chase Bank,0,US 1 and Pga Boulevard Branch,7955,07/15/2014,NaN,11364 US Highway 1,Palm Beach Gardens,Palm Beach,33408,26.84179,-80.06188,NaN,NaN,NaN,NaN,NaN,6.159000e+03,15358
FL,JPMorgan Chase Bank,0,San Marco Branch,7956,09/03/2014,NaN,11364 US Highway 1,Jacksonville,Duval,32219,30.44229,-81.76591,NaN,NaN,NaN,NaN,NaN,6.153000e+03,14266
IL,JPMorgan Chase Bank,0,Park and Greenbay Branch,7957,09/04/2014,NaN,332 Park Avenue,Glencoe,Cook,60022,42.13445,-87.75890,NaN,NaN,NaN,NaN,NaN,8.045000e+03,15646
NY,JPMorgan Chase Bank,0,Bedford Hills Branch,7958,11/04/2014,NaN,711 Bedford Road,Bedford Hills,Westchester,10507,41.22460,-73.71420,NaN,NaN,NaN,NaN,NaN,8.302000e+03,8848
FL,JPMorgan Chase Bank,0,Siesta and Tamiami Branch,7959,12/16/2014,NaN,3500 South Tamiami Trail,Sarasota,Sarasota,34239,27.30253,-82.53040,NaN,NaN,NaN,NaN,NaN,6.474000e+03,15235
CA,JPMorgan Chase Bank,0,Gellert and Westborough Branch,7960,01/27/2015,NaN,"2248 Westborough Boulevard, Suite 601 and 602",South San Francisco,San Mateo,94080,37.65573,-122.42804,NaN,NaN,NaN,NaN,NaN,5.406000e+03,15856
FL,JPMorgan Chase Bank,0,Federal Highway and 5th Avenue Branch,7961,02/10/2015,NaN,1850 North Federal Highway,Boca Raton,Palm Beach,33432,26.36682,-80.07848,NaN,NaN,NaN,NaN,NaN,1.742000e+03,7331
CT,JPMorgan Chase Bank,0,Norwalk Waypointe Branch,7962,04/14/2015,NaN,515 West Avenue,Norwalk,Fairfield,6850,41.11189,-73.41648,NaN,NaN,NaN,NaN,NaN,3.990000e+02,3888
FL,JPMorgan Chase Bank,0,Fleming Island Cr 220 Branch,7963,04/21/2015,NaN,1516 Cr 220,Fleming Island,Clay,32003,30.10245,-81.70911,NaN,NaN,NaN,NaN,NaN,2.914000e+03,10912
FL,JPMorgan Chase Bank,0,Manatee and 75th Branch,7964,04/23/2015,NaN,7206 Manatee Avenue West,Bradenton,Manatee,34209,27.49612,-82.63335,NaN,NaN,NaN,NaN,NaN,1.046600e+04,20377
CA,JPMorgan Chase Bank,0,Camino Alto & East Blithdale Banking Center,7965,07/21/2015,NaN,630 East Blithedale Ave,Mill Valley,Marin,94941,37.90032,-122.52838,NaN,NaN,NaN,NaN,NaN,NaN,18398
NJ,JPMorgan Chase Bank,0,North Flemington Branch,7967,07/21/2015,NaN,318 State Route 31,Flemington,Hunterdon,8822,40.53951,-74.85741,NaN,NaN,NaN,NaN,NaN,NaN,7399
FL,JPMorgan Chase Bank,0,Village Of Merrick Park Branch,7969,09/28/2015,NaN,4101 Ponce De Leon Blvd,Coral Gables,Miami-Dade,33146,25.73373,-80.25846,NaN,NaN,NaN,NaN,NaN,NaN,90046
FL,JPMorgan Chase Bank,0,Forest Hill Blvd and 441,7970,10/13/2015,NaN,10100 Forest Hill Blvd,Wellington,Palm Beach,33414,26.65059,-80.20469,NaN,NaN,NaN,NaN,NaN,NaN,8135
CO,JPMorgan Chase Bank,0,Easter and University Branch,7971,10/26/2015,NaN,6900 South University Blvd,Centennial,Arapahoe,80122,39.59193,-104.96018,NaN,NaN,NaN,NaN,NaN,NaN,55675
IL,JPMorgan Chase Bank,0,Hamilton and Jefferson Branch,7972,10/26/2015,NaN,125 Ne Jefferson Avenue,Peoria,Peoria,61602,40.69306,-89.59027,NaN,NaN,NaN,NaN,NaN,NaN,170769
FL,JPMorgan Chase Bank,0,Coconut Grove Branch,7973,11/10/2015,NaN,3015 Grand Avenue,Miami,Miami-Dade,33133,25.72817,-80.24199,NaN,NaN,NaN,NaN,NaN,NaN,6634
CA,JPMorgan Chase Bank,0,Park Place Branch,7974,11/17/2015,NaN,"2967 Michelson Drive, Suite A",Irvine,Orange,92612,33.67125,-117.84538,NaN,NaN,NaN,NaN,NaN,NaN,11600
CA,JPMorgan Chase Bank,0,LA Paz Road and Aliso Creek Branch,7975,12/03/2015,NaN,23970 Aliso Creek Road,Laguna Niguel,Orange,92677,33.55544,-117.71183,NaN,NaN,NaN,NaN,NaN,NaN,4809
OK,JPMorgan Chase Bank,0,Oklahoma City Downtown Branch,7976,12/07/2015,NaN,320 North Broadway Avenue,Oklahoma City,Oklahoma,73102,35.47050,-97.51438,NaN,NaN,NaN,NaN,NaN,NaN,2551581
FL,JPMorgan Chase Bank,0,Tampa Downtown Branch,7978,04/26/2016,NaN,300 North Franklin Street,Tampa,Hillsborough,33602,27.94710,-82.45770,NaN,NaN,NaN,NaN,NaN,NaN,684
FL,JPMorgan Chase Bank,0,Bartram Park and Old St. Augustine Branch,7979,05/10/2016,NaN,"13920 Old St. Augustine Road, Unit 107",Jacksonville,Duval,32258,30.14180,-81.54606,NaN,NaN,NaN,NaN,NaN,NaN,2271
CA,JPMorgan Chase Bank,0,Desoto and Ventura Branch,7980,05/24/2016,NaN,20900 Ventura Blvd,Woodland Hills,Los Angeles,91364,34.16641,-118.58866,NaN,NaN,NaN,NaN,NaN,NaN,2571
CA,JPMorgan Chase Bank,0,Alameda and Compton Blvd Branch,7981,11/03/2015,NaN,251 E Compton Blvd,Compton,Los Angeles,90220,33.89601,-118.22084,NaN,NaN,NaN,NaN,NaN,NaN,3446
NV,JPMorgan Chase Bank,0,Charleston and Rancho,7982,02/02/2016,NaN,2311 W Chafrleston Blvd,Las Vegas,Clark,89102,36.14270,-115.19043,NaN,NaN,NaN,NaN,NaN,NaN,2666
CA,JPMorgan Chase Bank,0,Los Olivos Branch,7984,03/15/2016,NaN,8593 Irvine Center Drive,Irvine,Orange,92618,33.64412,-117.74453,NaN,NaN,NaN,NaN,NaN,NaN,6689
LA,JPMorgan Chase Bank,0,Lake Forest Branch,7988,01/01/2016,NaN,5660 Read Blvd,New Orleans,Orleans,70127,30.03205,-89.97260,NaN,NaN,NaN,NaN,NaN,NaN,94133
NY,JPMorgan Chase Bank,0,Buffalo-Mm Branch,7989,01/01/2016,NaN,350 Main Street,Buffalo,Erie,14202,42.88429,-78.87487,NaN,NaN,NaN,NaN,NaN,NaN,45596

## Group All Rows Accordingly to State
- We can aggregate and ask for the sum total of State.  Or aggregate and ask for the mean.
- The function below aggregates all the data that corresponds to each State into one single row per State.  For example, if AZ has 256 rows out of 5,413 total rows, now it will all show as one mean of all the data into one single row.  Dataframe has 5,413 rows and we get 26 total rows after running the function below.

In [10]:
df2 = df1.groupby('State').mean()

df2

,Main Office,Branch Number,Zipcode,Latitude,Longitude,2010 Deposits,2011 Deposits,2012 Deposits,2013 Deposits,2014 Deposits,2015 Deposits,2016 Deposits
State,,,,,,,,,,,,
AZ,0.000000,3633.179688,85398.687500,33.383542,-111.899391,7.589532e+04,7.717828e+04,8.357267e+04,9.196123e+04,9.671907e+04,1.068692e+05,1.176833e+05
CA,0.000000,5913.613161,92805.446660,35.336353,-119.409642,8.322127e+04,8.205084e+04,8.260358e+04,8.545739e+04,9.236482e+04,1.026225e+05,1.186029e+05
CO,0.000000,4774.482456,80312.236842,39.755065,-104.976522,6.928259e+04,8.152999e+04,8.024558e+04,9.589530e+04,8.628163e+04,9.015160e+04,1.011298e+05
CT,0.000000,3319.280000,6753.000000,41.187905,-73.375007,8.899461e+04,9.124488e+04,9.220400e+04,9.616670e+04,9.800373e+04,1.000719e+05,1.106604e+05
DC,0.000000,4409.000000,20006.000000,38.900240,-77.038070,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
FL,0.000000,6309.313131,33396.648990,27.123376,-81.014857,4.433210e+04,4.721947e+04,4.885668e+04,5.250518e+04,5.708585e+04,6.327790e+04,7.282015e+04
GA,0.000000,6613.759036,30164.012048,33.892526,-84.334768,1.170818e+04,1.301828e+04,1.691926e+04,2.125203e+04,2.667870e+04,3.185718e+04,3.830489e+04
ID,0.000000,6381.050000,83621.650000,43.854341,-115.635778,1.914411e+04,1.909026e+04,2.031915e+04,2.137000e+04,2.493860e+04,2.889115e+04,3.369820e+04
IL,0.000000,3957.638814,60467.326146,41.400228,-87.017360,1.457416e+05,1.685098e+05,1.951250e+05,2.091494e+05,2.372494e+05,2.343950e+05,2.275081e+05
IN,0.000000,3155.175141,46546.960452,40.247763,-86.238464,7.072699e+04,7.101410e+04,7.576674e+04,8.109440e+04,8.879496e+04,9.506981e+04,1.010608e+05
KY,0.000000,3091.290323,40628.467742,38.144717,-85.291730,6.736108e+04,7.177548e+04,8.162852e+04,7.552977e+04,8.213735e+04,8.905647e+04,9.141194e+04
LA,0.000000,2338.798701,70635.077922,30.629858,-91.516504,8.927389e+04,9.189092e+04,9.970439e+04,1.061476e+05,1.094384e+05,1.146567e+05,1.142157e+05
MA,0.000000,4407.000000,2110.000000,42.355970,-71.049810,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
MI,0.000000,3024.394309,48530.886179,42.791790,-83.849739,8.434725e+04,1.011638e+05,1.150547e+05,1.263822e+05,1.465755e+05,1.584697e+05,1.707570e+05
NJ,0.000000,4513.926606,7700.325688,40.697085,-74.280608,4.938942e+04,5.584091e+04,5.738146e+04,6.551845e+04,7.221143e+04,7.861970e+04,8.830032e+04
NV,0.000000,6434.812500,89100.708333,36.122835,-115.177113,2.934353e+04,3.179887e+04,3.645212e+04,4.002855e+04,4.788460e+04,5.383404e+04,6.061888e+04
NY,0.000000,3011.433246,11139.099476,40.968160,-73.964581,3.849342e+05,4.713859e+05,5.245762e+05,5.651023e+05,6.064237e+05,6.274425e+05,7.025560e+05
OH,0.003509,2106.245614,44291.147368,40.376919,-82.660154,2.347836e+06,2.744006e+06,3.015689e+06,3.306157e+06,3.707993e+06,3.841918e+06,4.152946e+06
OK,0.000000,3428.093750,73409.968750,35.671267,-97.014822,5.154726e+04,5.202906e+04,5.638845e+04,6.025790e+04,6.864903e+04,6.859248e+04,1.518045e+05
OR,0.000000,5966.743363,97275.681416,44.726245,-122.713529,3.968529e+04,3.893520e+04,3.856117e+04,3.927763e+04,4.303623e+04,4.734976e+04,5.397746e+04
PA,0.000000,4406.000000,19103.000000,39.953090,-75.174020,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
TX,0.000000,3823.534848,76838.187879,31.118924,-96.833499,1.277518e+05,1.513263e+05,1.626560e+05,1.905592e+05,2.471923e+05,2.226196e+05,2.293845e+05
UT,0.000000,4602.203704,84194.203704,40.442665,-111.975328,1.267652e+05,1.240244e+05,6.785041e+04,8.165352e+04,7.883741e+04,2.242317e+05,2.353558e+05
WA,0.000000,5894.200980,98366.514706,47.394824,-121.753010,4.865160e+04,4.808073e+04,5.044664e+04,5.443459e+04,5.961238e+04,6.569906e+04,7.446892e+04
WI,0.000000,2896.148649,53671.797297,43.378328,-88.352818,7.746509e+04,9.133796e+04,9.855585e+04,1.067444e+05,1.144082e+05,1.264678e+05,1.271724e+05
WV,0.000000,1809.730769,25662.461538,38.511245,-81.466225,6.198619e+04,6.044546e+04,6.479338e+04,6.657346e+04,6.702327e+04,6.741323e+04,6.970138e+04

## Second Way of Aggregating
- Below is the example of grouping and asking for the sum instead of the mean().

In [11]:
df2 = df1.groupby('State').sum()

df2

,Main Office,Branch Number,Zipcode,Latitude,Longitude,2010 Deposits,2011 Deposits,2012 Deposits,2013 Deposits,2014 Deposits,2015 Deposits,2016 Deposits
State,,,,,,,,,,,,
AZ,0,930094,21862064,8512.80314,-28534.34458,18518457.0,19217392.0,21227459.0,23358152.0,2.476008e+07,2.735852e+07,30126930
CA,0,5931354,93083863,34629.62581,-117021.44869,59586426.0,63507350.0,71452096.0,80244493.0,9.134881e+07,1.022120e+08,118958728
CO,0,544291,9155595,4532.07743,-11967.32348,6997542.0,8642179.0,8827014.0,10836169.0,9.749824e+06,1.018713e+07,11528794
CT,0,165964,337650,1977.01942,-3522.00035,3648779.0,3832285.0,4241384.0,4519835.0,4.802183e+06,5.003594e+06,5533022
DC,0,4409,20006,38.90024,-77.03807,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0
FL,0,2498488,13225073,10279.75942,-30704.63079,9708730.0,11568770.0,14901287.0,18114286.0,2.135011e+07,2.474166e+07,28836780
GA,0,548942,2503613,2711.40211,-6746.78145,573701.0,833170.0,1235106.0,1657658.0,2.187653e+06,2.644146e+06,3179306
ID,0,127621,1672433,877.08682,-2312.71556,363738.0,362715.0,406383.0,427400.0,4.987720e+05,5.778230e+05,673964
IL,0,1468284,22433378,15276.68427,-32109.40570,47511768.0,56113765.0,68488872.0,74457178.0,8.707051e+07,8.672616e+07,84405502
IN,0,558466,8238812,7123.85408,-15264.20818,12447950.0,12569495.0,13410713.0,14353708.0,1.571671e+07,1.682736e+07,17887763
KY,0,191660,2518965,2364.97248,-5288.08726,4176387.0,4450080.0,5060968.0,4682846.0,5.092516e+06,5.521501e+06,5667540
LA,0,360175,10877802,4686.36827,-14002.02517,13569631.0,13967420.0,15155067.0,16134439.0,1.674408e+07,1.754247e+07,17589216
MA,0,4407,2110,42.35597,-71.04981,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0
MI,0,744001,11938598,10526.78037,-20627.03587,20580730.0,24785129.0,28303465.0,31090021.0,3.605758e+07,3.898354e+07,42006213
NJ,0,984036,1678671,8871.96447,-16193.17263,9532159.0,11112342.0,11877962.0,13824392.0,1.545324e+07,1.706048e+07,19249470
NV,0,308871,4276834,1661.65039,-5298.14719,997680.0,1240156.0,1567441.0,1881342.0,2.250576e+06,2.530200e+06,2909706
NY,0,2300735,8510272,30889.99275,-55769.29402,281001947.0,348825565.0,390809240.0,422696548.0,4.596692e+08,4.787386e+08,536752799
OH,1,600280,12622977,11467.04513,-23475.48377,650350577.0,762833720.0,853440012.0,938948496.0,1.056778e+09,1.094947e+09,1183589468
OK,0,109699,2349119,1141.48053,-3104.47429,1597965.0,1612901.0,1748042.0,1867995.0,2.128120e+06,2.126367e+06,4857743
OR,0,674242,10992152,5009.33947,-13743.91520,4008214.0,4010326.0,4241729.0,4438372.0,4.863094e+06,5.350523e+06,6099453
PA,0,4406,19103,39.95309,-75.17402,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0
TX,0,2523533,50713204,20445.13331,-63619.60887,79461631.0,95184270.0,105401093.0,125006852.0,1.631469e+08,1.469289e+08,151393753
UT,0,248519,4546487,2183.90392,-6046.66770,6084730.0,6325245.0,3663922.0,4409290.0,4.257220e+06,1.210851e+07,12709215
WA,0,1202417,20066769,9668.54413,-24837.61408,9000546.0,9327661.0,10038882.0,10995788.0,1.216092e+07,1.340261e+07,15191659
WI,0,214315,3971713,3209.99624,-6538.10854,5732417.0,6759009.0,7293133.0,7899084.0,8.466207e+06,9.358616e+06,9410758
WV,0,47053,667224,1001.29237,-2118.12184,1611641.0,1571582.0,1684628.0,1730910.0,1.742605e+06,1.752744e+06,1812236

## Select Desired Columns
- The columns 'Branch Number', 'Zipcode', 'Latitude',and  'Longitude' are not useful anymore.  All the zipcodes are sumed up and meaningless to use.  Same for the mentioned columns as well.  But we can drop and get rid of those columns and keep what we need using the below example.

In [12]:
df3 = df2.iloc[:, 5:]

df3

,2010 Deposits,2011 Deposits,2012 Deposits,2013 Deposits,2014 Deposits,2015 Deposits,2016 Deposits
State,,,,,,,
AZ,18518457.0,19217392.0,21227459.0,23358152.0,2.476008e+07,2.735852e+07,30126930
CA,59586426.0,63507350.0,71452096.0,80244493.0,9.134881e+07,1.022120e+08,118958728
CO,6997542.0,8642179.0,8827014.0,10836169.0,9.749824e+06,1.018713e+07,11528794
CT,3648779.0,3832285.0,4241384.0,4519835.0,4.802183e+06,5.003594e+06,5533022
DC,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0
FL,9708730.0,11568770.0,14901287.0,18114286.0,2.135011e+07,2.474166e+07,28836780
GA,573701.0,833170.0,1235106.0,1657658.0,2.187653e+06,2.644146e+06,3179306
ID,363738.0,362715.0,406383.0,427400.0,4.987720e+05,5.778230e+05,673964
IL,47511768.0,56113765.0,68488872.0,74457178.0,8.707051e+07,8.672616e+07,84405502
IN,12447950.0,12569495.0,13410713.0,14353708.0,1.571671e+07,1.682736e+07,17887763
KY,4176387.0,4450080.0,5060968.0,4682846.0,5.092516e+06,5.521501e+06,5667540
LA,13569631.0,13967420.0,15155067.0,16134439.0,1.674408e+07,1.754247e+07,17589216
MA,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0
MI,20580730.0,24785129.0,28303465.0,31090021.0,3.605758e+07,3.898354e+07,42006213
NJ,9532159.0,11112342.0,11877962.0,13824392.0,1.545324e+07,1.706048e+07,19249470
NV,997680.0,1240156.0,1567441.0,1881342.0,2.250576e+06,2.530200e+06,2909706
NY,281001947.0,348825565.0,390809240.0,422696548.0,4.596692e+08,4.787386e+08,536752799
OH,650350577.0,762833720.0,853440012.0,938948496.0,1.056778e+09,1.094947e+09,1183589468
OK,1597965.0,1612901.0,1748042.0,1867995.0,2.128120e+06,2.126367e+06,4857743
OR,4008214.0,4010326.0,4241729.0,4438372.0,4.863094e+06,5.350523e+06,6099453
PA,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0
TX,79461631.0,95184270.0,105401093.0,125006852.0,1.631469e+08,1.469289e+08,151393753
UT,6084730.0,6325245.0,3663922.0,4409290.0,4.257220e+06,1.210851e+07,12709215
WA,9000546.0,9327661.0,10038882.0,10995788.0,1.216092e+07,1.340261e+07,15191659
WI,5732417.0,6759009.0,7293133.0,7899084.0,8.466207e+06,9.358616e+06,9410758
WV,1611641.0,1571582.0,1684628.0,1730910.0,1.742605e+06,1.752744e+06,1812236

## Note from the Above Example
- The first : inside square brackets denotes all the rows, and the second : after number 5 denotes all the columns after the fifth column.  So, instead we can try [:, 5:6] which means all the rows and only the fifth and sixth column are to be selected from the entire dataframe.
- Same goes for the rows.  So, at the first : we can place a number in front or after like this [4:, 5:] which will return all the rows after the fourth row (excluding the first four).  Or the opposite [:4, 5:] which will return only the first 4 rows.

## Method describe()
- Computes common aggregates for each column and returns the result.  It is an easy and short method that provides a lot of information.  It summarizes the data and gives understanding of what values we have, what story do we see, and what can we do and show.

In [13]:
df3.describe()

,2010 Deposits,2011 Deposits,2012 Deposits,2013 Deposits,2014 Deposits,2015 Deposits,2016 Deposits
count,2.600000e+01,2.600000e+01,2.600000e+01,2.600000e+01,2.600000e+01,2.600000e+01,2.600000e+01
mean,4.796397e+07,5.648664e+07,6.324907e+07,6.975289e+07,7.870365e+07,8.163962e+07,8.886039e+07
std,1.350215e+08,1.598470e+08,1.789220e+08,1.963973e+08,2.202840e+08,2.279255e+08,2.476405e+08
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.601384e+06,1.581912e+06,1.700482e+06,1.871332e+06,2.203384e+06,2.558686e+06,3.598915e+06
50%,6.541136e+06,7.700594e+06,8.060074e+06,9.367626e+06,9.108016e+06,1.114782e+07,1.211900e+07
75%,1.728125e+07,1.790490e+07,1.970936e+07,2.204719e+07,2.390759e+07,2.670431e+07,2.980439e+07
max,6.503506e+08,7.628337e+08,8.534400e+08,9.389485e+08,1.056778e+09,1.094947e+09,1.183589e+09

## Get Rid of Rows
- If you look at the above data, rows that correspond to 'DC', 'PA', & 'MA' have 0 values.  We can get rid of those rows and have a better data frame to use by doing the following:

In [14]:
df4 = df3.drop(['DC', 'MA', 'PA'])
df4

,2010 Deposits,2011 Deposits,2012 Deposits,2013 Deposits,2014 Deposits,2015 Deposits,2016 Deposits
State,,,,,,,
AZ,18518457.0,19217392.0,21227459.0,23358152.0,2.476008e+07,2.735852e+07,30126930
CA,59586426.0,63507350.0,71452096.0,80244493.0,9.134881e+07,1.022120e+08,118958728
CO,6997542.0,8642179.0,8827014.0,10836169.0,9.749824e+06,1.018713e+07,11528794
CT,3648779.0,3832285.0,4241384.0,4519835.0,4.802183e+06,5.003594e+06,5533022
FL,9708730.0,11568770.0,14901287.0,18114286.0,2.135011e+07,2.474166e+07,28836780
GA,573701.0,833170.0,1235106.0,1657658.0,2.187653e+06,2.644146e+06,3179306
ID,363738.0,362715.0,406383.0,427400.0,4.987720e+05,5.778230e+05,673964
IL,47511768.0,56113765.0,68488872.0,74457178.0,8.707051e+07,8.672616e+07,84405502
IN,12447950.0,12569495.0,13410713.0,14353708.0,1.571671e+07,1.682736e+07,17887763
KY,4176387.0,4450080.0,5060968.0,4682846.0,5.092516e+06,5.521501e+06,5667540
LA,13569631.0,13967420.0,15155067.0,16134439.0,1.674408e+07,1.754247e+07,17589216
MI,20580730.0,24785129.0,28303465.0,31090021.0,3.605758e+07,3.898354e+07,42006213
NJ,9532159.0,11112342.0,11877962.0,13824392.0,1.545324e+07,1.706048e+07,19249470
NV,997680.0,1240156.0,1567441.0,1881342.0,2.250576e+06,2.530200e+06,2909706
NY,281001947.0,348825565.0,390809240.0,422696548.0,4.596692e+08,4.787386e+08,536752799
OH,650350577.0,762833720.0,853440012.0,938948496.0,1.056778e+09,1.094947e+09,1183589468
OK,1597965.0,1612901.0,1748042.0,1867995.0,2.128120e+06,2.126367e+06,4857743
OR,4008214.0,4010326.0,4241729.0,4438372.0,4.863094e+06,5.350523e+06,6099453
TX,79461631.0,95184270.0,105401093.0,125006852.0,1.631469e+08,1.469289e+08,151393753
UT,6084730.0,6325245.0,3663922.0,4409290.0,4.257220e+06,1.210851e+07,12709215
WA,9000546.0,9327661.0,10038882.0,10995788.0,1.216092e+07,1.340261e+07,15191659
WI,5732417.0,6759009.0,7293133.0,7899084.0,8.466207e+06,9.358616e+06,9410758
WV,1611641.0,1571582.0,1684628.0,1730910.0,1.742605e+06,1.752744e+06,1812236

## Select Only One Row
- Select only one state, in this case WV, and show all its variables/ columns.

In [15]:
df4.loc['WV']

2010 Deposits    1611641.0
2011 Deposits    1571582.0
2012 Deposits    1684628.0
2013 Deposits    1730910.0
2014 Deposits    1742605.0
2015 Deposits    1752744.0
2016 Deposits    1812236.0
Name: WV, dtype: float64

## Select Only a Certain Row
- Example below selects only the rows that belong to Arizona.  There are 256 rows and 20 columns out of 5,413 that match with Arizona.

In [16]:
df5 = data[data.State == 'AZ']
df5

,Institution Name,Main Office,Branch Name,Branch Number,Established Date,Acquired Date,Street Address,City,County,State,Zipcode,Latitude,Longitude,2010 Deposits,2011 Deposits,2012 Deposits,2013 Deposits,2014 Deposits,2015 Deposits,2016 Deposits
1234,JPMorgan Chase Bank,0,Chase Tower Branch,2414,01/01/1899,11/13/2004,201 North Central Avenue,Phoenix,Maricopa,AZ,85004,33.45091,-112.07382,4246556.0,4270187.0,4836020.0,5582684.0,5857726.0,6909171.0,7822138
1235,JPMorgan Chase Bank,0,Buckeye Branch,2415,11/15/1954,11/13/2004,402 Monroe Avenue,Buckeye,Maricopa,AZ,85326,33.37048,-112.58601,77689.0,78517.0,84900.0,86839.0,89189.0,85675.0,87678
1236,JPMorgan Chase Bank,0,Carefree Branch,2416,11/11/1963,11/13/2004,7206 E Wampum Way,Carefree,Maricopa,AZ,85377,33.82381,-111.92367,109277.0,118074.0,122861.0,134441.0,146003.0,161810.0,179433
1237,JPMorgan Chase Bank,0,Glendale Main Branch,2419,01/01/1899,11/13/2004,7003 North 57th Drive,Glendale,Maricopa,AZ,85301,33.53922,-112.18237,62170.0,64008.0,63265.0,67601.0,66172.0,62080.0,66725
1238,JPMorgan Chase Bank,0,Grand Canyon Branch,2420,06/03/1963,11/13/2004,1 Mather Business Center,Grand Canyon,Coconino,AZ,86023,36.05444,-112.12058,16695.0,15849.0,18657.0,21822.0,18887.0,23347.0,25858
1239,JPMorgan Chase Bank,0,Lake Havasu Branch,2421,09/08/1964,11/13/2004,1895 Mcculloch Boulevard,Lake Havasu City,Mohave,AZ,86403,34.47598,-114.33041,128321.0,135568.0,148504.0,155359.0,175393.0,210256.0,185592
1240,JPMorgan Chase Bank,0,Camelback and 59th Avenue Branch,2422,05/23/1960,11/13/2004,5740 West Camelback Road,Glendale,Maricopa,AZ,85301,33.50956,-112.18342,65135.0,70539.0,70871.0,72814.0,70809.0,75869.0,78443
1241,JPMorgan Chase Bank,0,Mcdowelland 74th Street Branch,2423,11/19/1962,11/13/2004,7345 East Mcdowell Road,Scottsdale,Maricopa,AZ,85257,33.46568,-111.92225,89342.0,86107.0,93190.0,102311.0,104682.0,110227.0,125235
1242,JPMorgan Chase Bank,0,Mesa Main Branch,2424,01/01/1899,11/13/2004,61 N Country Club Dr,Mesa,Maricopa,AZ,85201,33.41655,-111.83995,118024.0,118856.0,127272.0,131269.0,139484.0,261451.0,191874
1243,JPMorgan Chase Bank,0,Payson Branch,2426,06/02/1958,11/13/2004,201 South Beeline Highway,Payson,Gila,AZ,85541,34.23896,-111.32291,94989.0,92519.0,94124.0,97611.0,106744.0,113873.0,124282
1244,JPMorgan Chase Bank,0,Camelback And16th Street Branch,2427,04/16/1956,11/13/2004,5041 North 16th Street,Phoenix,Maricopa,AZ,85016,33.51080,-112.04752,88942.0,92032.0,108805.0,127857.0,125134.0,137805.0,122655
1245,JPMorgan Chase Bank,0,Indian School and 33rd Avenue Branch,2428,06/15/1964,11/13/2004,3241 West Indian School Road,Phoenix,Maricopa,AZ,85017,33.49483,-112.12867,44441.0,52768.0,53056.0,53625.0,57847.0,60986.0,70922
1246,JPMorgan Chase Bank,0,Buckeye And16th Street Branch,2429,09/14/1964,11/13/2004,1528 East Buckeye Road,Phoenix,Maricopa,AZ,85034,33.43687,-112.04877,28297.0,27775.0,26569.0,27648.0,29084.0,33353.0,35823
1247,JPMorgan Chase Bank,0,Central and Columbus Branch,2430,09/15/1951,11/13/2004,3620 N Central Avenue,Phoenix,Maricopa,AZ,85012,33.48987,-112.07395,150239.0,145516.0,150937.0,157414.0,144297.0,149819.0,154987
1248,JPMorgan Chase Bank,0,Glendale and 7th Street Branch,2431,05/09/1960,11/13/2004,7022 North Seventh Street,Phoenix,Maricopa,AZ,85020,33.53900,-112.06508,166154.0,172256.0,202468.0,221069.0,227735.0,246998.0,261735
1249,JPMorgan Chase Bank,0,Bethany Home and 19th Avenue Branch,2432,08/24/1961,11/13/2004,6030 North 19th Avenue,Phoenix,Maricopa,AZ,85015,33.52529,-112.09969,56016.0,64878.0,63780.0,62050.0,60482.0,61104.0,65492
1250,JPMorgan Chase Bank,0,West Van Buren Branch,2433,12/20/1948,11/13/2004,1820 West Van Buren Street,Phoenix,Maricopa,AZ,85007,33.45126,-112.09912,46441.0,48974.0,55892.0,56820.0,59417.0,67323.0,68162
1251,JPMorgan Chase Bank,0,Camelback and 44th Street Branch,2434,12/18/1961,11/13/2004,4401 East Camelback Road,Phoenix,Maricopa,AZ,85018,33.50942,-111.98620,182481.0,189831.0,194090.0,201376.0,224536.0,259378.0,270293
1252,JPMorgan Chase Bank,0,Thomas and 24th Street Branch,2435,12/20/1954,11/13/2004,3001 North 24th Street,Phoenix,Maricopa,AZ,85016,33.48248,-112.03020,63619.0,58866.0,52485.0,50692.0,49920.0,51254.0,56939
1253,JPMorgan Chase Bank,0,Thomas and 7th Avenue Branch,2436,01/27/1958,11/13/2004,2901 North Seventh Avenue,Phoenix,Maricopa,AZ,85013,33.48094,-112.08303,96956.0,100821.0,106304.0,103803.0,111474.0,116476.0,130378
1254,JPMorgan Chase Bank,0,Prescott Branch,2437,01/01/1899,11/13/2004,302 West Gurley Street,Prescott,Yavapai,AZ,86301,34.54192,-112.47189,95826.0,95300.0,111556.0,124425.0,137870.0,130456.0,140013
1255,JPMorgan Chase Bank,0,Safford Branch,2438,01/01/1899,11/13/2004,321 West Main Street,Safford,Graham,AZ,85546,32.83321,-109.71030,104308.0,103406.0,110504.0,112276.0,122715.0,126474.0,124318
1256,JPMorgan Chase Bank,0,San Luis Branch,2439,04/06/1964,11/13/2004,623 North Main Street,San Luis,Yuma,AZ,85349,32.48887,-114.78232,91421.0,88603.0,87296.0,89722.0,84489.0,77663.0,86777
1257,JPMorgan Chase Bank,0,Scottsdale Road-Shea Blvd. Branch,2440,12/07/1964,11/13/2004,10350 North Scottsdale Road,Scottsdale,Maricopa,AZ,85253,33.58140,-111.92611,112020.0,116497.0,122311.0,129934.0,142041.0,143649.0,157065
1258,JPMorgan Chase Bank,0,Scottsdale Branch,2441,11/03/1958,11/13/2004,4031 North Scottsdale Road,Scottsdale,Maricopa,AZ,85251,33.49447,-111.92613,176970.0,160512.0,157239.0,176842.0,206114.0,217906.0,216429
1259,JPMorgan Chase Bank,0,Show Low Branch,2442,03/05/1956,11/13/2004,400 N White Mountan Road,Show Low,Navajo,AZ,85901,34.25285,-110.02869,73246.0,72264.0,90542.0,86041.0,99891.0,109921.0,120549
1260,JPMorgan Chase Bank,0,South Tucson Branch,2443,11/17/1952,11/13/2004,1818 South 6th Avenue,Tucson,Pima,AZ,85713,32.19971,-110.96846,25398.0,26887.0,28342.0,30764.0,29228.0,30044.0,32473
1261,JPMorgan Chase Bank,0,University and Mill Branch,2444,12/04/1961,11/13/2004,830 S Mill Ave,Tempe,Maricopa,AZ,85281,33.42079,-111.94004,69934.0,80678.0,90559.0,101951.0,111939.0,132047.0,155089
1262,JPMorgan Chase Bank,0,Tuscon Downtown Branch,2445,02/11/1935,11/13/2004,2 East Congress Street,Tucson,Pima,AZ,85701,32.22189,-110.97098,422106.0,340106.0,367268.0,328480.0,327343.0,313910.0,400082
1263,JPMorgan Chase Bank,0,Wilmont and 22nd Street Branch,2446,01/11/1960,11/13/2004,6161 East 22nd Street,Tucson,Pima,AZ,85711,32.20705,-110.86113,50994.0,50055.0,51042.0,52069.0,53182.0,57779.0,57255
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4423,JPMorgan Chase Bank,0,Anthem Way and Vision Branch,6809,11/25/2008,NaN,4311 W Anthem Way,Phoenix,Maricopa,AZ,85086,33.83924,-112.10758,9360.0,12278.0,19072.0,22096.0,27834.0,29904.0,35315
4424,JPMorgan Chase Bank,0,Chandler Heights and Arizona Ave Branch,6810,12/15/2008,NaN,228 W Chandler Heights Rd,Chandler,Maricopa,AZ,85248,33.23308,-111.84863,13164.0,19890.0,28483.0,41193.0,50052.0,52264.0,60319
4425,JPMorgan Chase Bank,0,Indian School and 32nd St Branch,6811,03/24/2009,NaN,3150 E Indian School Rd,Phoenix,Maricopa,AZ,85016,33.49524,-112.01449,6189.0,8207.0,17689.0,21313.0,21293.0,26966.0,29182
4426,JPMorgan Chase Bank,0,Tangerine and Thornydale Branch,6812,04/21/2009,NaN,12025 N Thornydale Rd,Marana,Pima,AZ,85658,32.42518,-111.04668,11798.0,13312.0,19947.0,25463.0,30602.0,42421.0,40158
4427,JPMorgan Chase Bank,0,Happy Valley and 39th Ave Branch,6813,04/28/2009,NaN,3880 W Happy Valley Rd,Glendale,Maricopa,AZ,85310,33.71285,-112.14326,7508.0,15068.0,21182.0,32509.0,39063.0,45019.0,50428
4429,JPMorgan Chase Bank,0,Greenway and 303 Frys Branch,6815,06/24/2009,NaN,15215 N Cotton Ln,Surprise,Maricopa,AZ,85388,33.62343,-112.42667,1598.0,3106.0,5057.0,6044.0,7456.0,8372.0,11488
4537,JPMorgan Chase Bank,0,Estrella and Pebble Creek Branch,6971,10/24/2008,NaN,2071 N Pebble Creek Pkwy,Goodyear,Maricopa,AZ,85395,33.46976,-112.39225,9621.0,14148.0,19401.0,26141.0,35342.0,42923.0,50301
4538,JPMorgan Chase Bank,0,Cactus and Reems Branch,6972,12/09/2008,NaN,15481 W Cactus Rd,Surprise,Maricopa,AZ,85379,33.59506,-112.39847,4465.0,6773.0,9327.0,16844.0,19179.0,22191.0,28376
4539,JPMorgan Chase Bank,0,Baseline and Greenfield Branch,6973,04/21/2009,NaN,1565 N Greenfield Rd,Gilbert,Maricopa,AZ,85234,33.37802,-111.73947,6517.0,9378.0,15775.0,21213.0,23408.0,30562.0,40847
4569,JPMorgan Chase Bank,0,Northern & 91st Avenue Banking Center Branch,7006,09/15/2009,NaN,9028 West Northern Avenue,Glendale,Maricopa,AZ,85305,33.55179,-112.25373,2912.0,9424.0,9559.0,11892.0,13417.0,22836.0,27501
4570,JPMorgan Chase Bank,0,Florence & I-10 Banking Center Branch,7007,09/15/2009,NaN,2437 East Florence Boulevard,Casa Grande,Pinal,AZ,85194,32.87958,-111.68388,3400.0,6451.0,9854.0,14923.0,17482.0,20464.0,24980
4573,JPMorgan Chase Bank,0,Highway 69 & Sundog Ranch Road Banking Center,7010,10/06/2009,NaN,5697 East State Route 69,Prescott Valley,Yavapai,AZ,86314,34.59701,-112.32299,4702.0,7989.0,13524.0,16907.0,20581.0,24217.0,28177
4617,JPMorgan Chase Bank,0,Montebello & 19th Ave Bnk Ctr Branch,7056,12/15/2009,NaN,5705 North 19th Avenue,Phoenix,Maricopa,AZ,85015,33.52105,-112.09950,2235.0,5785.0,9518.0,11793.0,14932.0,17193.0,21627
4621,JPMorgan Chase Bank,0,Happy Valley & I 17 Bnkg Ctr Branch,7060,12/15/2009,NaN,2430 West Happy Valley Road,Phoenix,Maricopa,AZ,85085,33.76177,-112.11085,6184.0,13291.0,23689.0,34942.0,49957.0,65796.0,68453
4630,JPMorgan Chase Bank,0,Thomas and Scottsdale Road Branch,7069,02/16/2010,NaN,2902 North Scottsdale Road,Scottsdale,Maricopa,AZ,85251,33.48048,-111.92625,2157.0,10032.0,18066.0,23464.0,29904.0,33223.0,40058
4631,JPMorgan Chase Bank,0,Prescott Valley Frys Bnkg Ctr Branch,7070,01/06/2010,NaN,3100 North Glassford Hill Road,Prescott Valley,Yavapai,AZ,86314,34.58745,-112.33968,647.0,1822.0,3208.0,5149.0,5592.0,5993.0,8628
4647,JPMorgan Chase Bank,0,Mayo & Scottsdale Banking Ctr Branch,7089,05/18/2010,NaN,7165 East Mayo Blvd,Phoenix,Maricopa,AZ,85054,33.68284,-111.94723,1849.0,15504.0,17904.0,26906.0,33395.0,36278.0,43715
4652,JPMorgan Chase Bank,0,Hwy 95 and Long Ave Branch,7104,08/18/2009,NaN,"3699 Hwy 95, Ste 900",Bullhead City,Mohave,AZ,86442,35.05206,-114.58908,8861.0,19703.0,27214.0,31436.0,33338.0,37235.0,44086
4679,JPMorgan Chase Bank,0,Mcdowell & 7th St Banking Ctr Branch,7136,07/13/2010,NaN,1601 North 7th Street,Phoenix,Maricopa,AZ,85006,33.46623,-112.06500,NaN,4421.0,8074.0,10082.0,12149.0,16120.0,19843
4686,JPMorgan Chase Bank,0,Baseline & Gilbert Fry's Bnkg Ctr Br,7145,09/08/2010,NaN,1845 East Baseline,Gilbert,Maricopa,AZ,85233,33.37886,-111.79174,NaN,2837.0,4545.0,6519.0,25079.0,28929.0,29705
4700,JPMorgan Chase Bank,0,Southern & Stapley Banking Center Branch,7172,10/26/2010,NaN,1054 East Southern Avenue,Mesa,Maricopa,AZ,85204,33.39341,-111.80860,NaN,2797.0,5691.0,7347.0,10802.0,13204.0,15316
4701,JPMorgan Chase Bank,0,Elliot & Estrella Banking Ctr Branch,7173,10/20/2010,NaN,9846 South Estrella Pkwy,Goodyear,Maricopa,AZ,85338,33.35788,-112.42417,NaN,5304.0,10045.0,15617.0,20593.0,27034.0,34184
4760,JPMorgan Chase Bank,0,Via Linda and Pima Frys Branch,7263,09/01/2010,NaN,8900 E Via Linda,Scottsdale,Maricopa,AZ,85258,33.56880,-111.88800,NaN,3678.0,5805.0,8420.0,11126.0,12144.0,13375
4871,JPMorgan Chase Bank,0,I8 & Fortuna Banking Center Branch,7403,10/18/2011,NaN,11225 South Frontage Road,Yuma,Yuma,AZ,85367,32.66924,-114.44228,NaN,NaN,7627.0,14976.0,24762.0,29262.0,35266
4921,JPMorgan Chase Bank,0,Camelback & 7th Banking Center Branch,7456,02/07/2012,NaN,675 East Camelback Road,Phoenix,Maricopa,AZ,85012,33.50921,-112.06521,NaN,NaN,3126.0,9744.0,27161.0,26097.0,18774
4973,JPMorgan Chase Bank,0,Carefree and 48th St Frys Branch,7510,07/01/2011,NaN,"4815 East Carefree Highway, Suite 100",Cave Creek,Maricopa,AZ,85331,33.79908,-111.97785,NaN,NaN,18981.0,21728.0,23791.0,22520.0,26732
4974,JPMorgan Chase Bank,0,Sierra Vista Frys Branch,7511,07/01/2011,NaN,4351 East Highway 90,Sierra Vista,Cochise,AZ,85635,31.55470,-110.25310,NaN,NaN,11722.0,12234.0,12652.0,13351.0,14607
5033,JPMorgan Chase Bank,0,Queen Creek and Higley Branch,7575,12/06/2011,NaN,4718 South Higley Road,Gilbert,Maricopa,AZ,85297,33.27632,-111.72063,NaN,NaN,3656.0,10911.0,13568.0,17587.0,23358
5249,JPMorgan Chase Bank,0,Apache & Rural Banking Center,7808,09/24/2013,NaN,"922 East Apache Blvd, Suite 105",Tempe,Maricopa,AZ,85281,33.41489,-111.92572,NaN,NaN,NaN,NaN,1804.0,4974.0,8203
5267,JPMorgan Chase Bank,0,Ellsworth & Baseline Banking Center,7826,10/28/2013,NaN,9155 East Baseline Road,Mesa,Maricopa,AZ,85209,33.37908,-111.63680,NaN,NaN,NaN,NaN,17440.0,28198.0,33001

## Rank Data (Ascending Order)
- Rank the data in ascending order.  The example below lists the smallest number first by specifying (..ascending=True).  We get the same result using (...ascending=1).

In [17]:
ranked1 = df4.sort_values('2010 Deposits', ascending=True)
ranked1

,2010 Deposits,2011 Deposits,2012 Deposits,2013 Deposits,2014 Deposits,2015 Deposits,2016 Deposits
State,,,,,,,
ID,363738.0,362715.0,406383.0,427400.0,4.987720e+05,5.778230e+05,673964
GA,573701.0,833170.0,1235106.0,1657658.0,2.187653e+06,2.644146e+06,3179306
NV,997680.0,1240156.0,1567441.0,1881342.0,2.250576e+06,2.530200e+06,2909706
OK,1597965.0,1612901.0,1748042.0,1867995.0,2.128120e+06,2.126367e+06,4857743
WV,1611641.0,1571582.0,1684628.0,1730910.0,1.742605e+06,1.752744e+06,1812236
CT,3648779.0,3832285.0,4241384.0,4519835.0,4.802183e+06,5.003594e+06,5533022
OR,4008214.0,4010326.0,4241729.0,4438372.0,4.863094e+06,5.350523e+06,6099453
KY,4176387.0,4450080.0,5060968.0,4682846.0,5.092516e+06,5.521501e+06,5667540
WI,5732417.0,6759009.0,7293133.0,7899084.0,8.466207e+06,9.358616e+06,9410758
UT,6084730.0,6325245.0,3663922.0,4409290.0,4.257220e+06,1.210851e+07,12709215
CO,6997542.0,8642179.0,8827014.0,10836169.0,9.749824e+06,1.018713e+07,11528794
WA,9000546.0,9327661.0,10038882.0,10995788.0,1.216092e+07,1.340261e+07,15191659
NJ,9532159.0,11112342.0,11877962.0,13824392.0,1.545324e+07,1.706048e+07,19249470
FL,9708730.0,11568770.0,14901287.0,18114286.0,2.135011e+07,2.474166e+07,28836780
IN,12447950.0,12569495.0,13410713.0,14353708.0,1.571671e+07,1.682736e+07,17887763
LA,13569631.0,13967420.0,15155067.0,16134439.0,1.674408e+07,1.754247e+07,17589216
AZ,18518457.0,19217392.0,21227459.0,23358152.0,2.476008e+07,2.735852e+07,30126930
MI,20580730.0,24785129.0,28303465.0,31090021.0,3.605758e+07,3.898354e+07,42006213
IL,47511768.0,56113765.0,68488872.0,74457178.0,8.707051e+07,8.672616e+07,84405502
CA,59586426.0,63507350.0,71452096.0,80244493.0,9.134881e+07,1.022120e+08,118958728
TX,79461631.0,95184270.0,105401093.0,125006852.0,1.631469e+08,1.469289e+08,151393753
NY,281001947.0,348825565.0,390809240.0,422696548.0,4.596692e+08,4.787386e+08,536752799
OH,650350577.0,762833720.0,853440012.0,938948496.0,1.056778e+09,1.094947e+09,1183589468

## Rank Data (Descending Order)
- Rank the data in descending order.  The example below lists the biggest number first by specifying (...ascending=False) same as (...ascending=0).

In [18]:
ranked2 = df4.sort_values('2011 Deposits', ascending=False)
ranked2

,2010 Deposits,2011 Deposits,2012 Deposits,2013 Deposits,2014 Deposits,2015 Deposits,2016 Deposits
State,,,,,,,
OH,650350577.0,762833720.0,853440012.0,938948496.0,1.056778e+09,1.094947e+09,1183589468
NY,281001947.0,348825565.0,390809240.0,422696548.0,4.596692e+08,4.787386e+08,536752799
TX,79461631.0,95184270.0,105401093.0,125006852.0,1.631469e+08,1.469289e+08,151393753
CA,59586426.0,63507350.0,71452096.0,80244493.0,9.134881e+07,1.022120e+08,118958728
IL,47511768.0,56113765.0,68488872.0,74457178.0,8.707051e+07,8.672616e+07,84405502
MI,20580730.0,24785129.0,28303465.0,31090021.0,3.605758e+07,3.898354e+07,42006213
AZ,18518457.0,19217392.0,21227459.0,23358152.0,2.476008e+07,2.735852e+07,30126930
LA,13569631.0,13967420.0,15155067.0,16134439.0,1.674408e+07,1.754247e+07,17589216
IN,12447950.0,12569495.0,13410713.0,14353708.0,1.571671e+07,1.682736e+07,17887763
FL,9708730.0,11568770.0,14901287.0,18114286.0,2.135011e+07,2.474166e+07,28836780
NJ,9532159.0,11112342.0,11877962.0,13824392.0,1.545324e+07,1.706048e+07,19249470
WA,9000546.0,9327661.0,10038882.0,10995788.0,1.216092e+07,1.340261e+07,15191659
CO,6997542.0,8642179.0,8827014.0,10836169.0,9.749824e+06,1.018713e+07,11528794
WI,5732417.0,6759009.0,7293133.0,7899084.0,8.466207e+06,9.358616e+06,9410758
UT,6084730.0,6325245.0,3663922.0,4409290.0,4.257220e+06,1.210851e+07,12709215
KY,4176387.0,4450080.0,5060968.0,4682846.0,5.092516e+06,5.521501e+06,5667540
OR,4008214.0,4010326.0,4241729.0,4438372.0,4.863094e+06,5.350523e+06,6099453
CT,3648779.0,3832285.0,4241384.0,4519835.0,4.802183e+06,5.003594e+06,5533022
OK,1597965.0,1612901.0,1748042.0,1867995.0,2.128120e+06,2.126367e+06,4857743
WV,1611641.0,1571582.0,1684628.0,1730910.0,1.742605e+06,1.752744e+06,1812236
NV,997680.0,1240156.0,1567441.0,1881342.0,2.250576e+06,2.530200e+06,2909706
GA,573701.0,833170.0,1235106.0,1657658.0,2.187653e+06,2.644146e+06,3179306
ID,363738.0,362715.0,406383.0,427400.0,4.987720e+05,5.778230e+05,673964

## Add Column
- We can add a column in the dataframe and also rank it.

In [19]:
df4['rank_column'] = df4['2010 Deposits'].rank(ascending=False)
data

,Institution Name,Main Office,Branch Name,Branch Number,Established Date,Acquired Date,Street Address,City,County,State,Zipcode,Latitude,Longitude,2010 Deposits,2011 Deposits,2012 Deposits,2013 Deposits,2014 Deposits,2015 Deposits,2016 Deposits
0,JPMorgan Chase Bank,1,JPMorgan Chase Bank Main Office,0,01/01/1824,NaN,1111 Polaris Parkway,Columbus,Delaware,OH,43240,40.14453,-82.99115,633131000.0,743268000.0,832455000.0,916543000.0,1.032549e+09,1.069425e+09,1155185000
1,JPMorgan Chase Bank,0,Vernon Hills Scarsdale Branch,2,03/20/1961,NaN,676 White Plains Road,Scarsdale,Westchester,NY,10583,40.97008,-73.80670,293229.0,310791.0,325742.0,327930.0,3.277920e+05,3.414750e+05,381558
2,JPMorgan Chase Bank,0,Great Neck Northern Boulevard Branch,3,09/09/1963,NaN,410 Northern Boulevard,Great Neck,Nassau,NY,11021,40.77944,-73.72240,191011.0,206933.0,216439.0,237983.0,2.341830e+05,2.624550e+05,278940
3,JPMorgan Chase Bank,0,North Hartsdale Branch,4,02/19/1966,NaN,353 North Central Avenue,Hartsdale,Westchester,NY,10530,41.02654,-73.79168,87110.0,88367.0,93163.0,109659.0,1.119850e+05,1.167720e+05,140233
4,JPMorgan Chase Bank,0,Lawrence Rockaway Branch,5,01/16/1965,NaN,335 Rockaway Turnpike,Lawrence,Nassau,NY,11559,40.62715,-73.73675,172608.0,172749.0,189413.0,198445.0,2.051980e+05,2.232000e+05,235594
5,JPMorgan Chase Bank,0,Mount Vernon Branch,9,02/25/1964,NaN,22 West First Street,Mount Vernon,Westchester,NY,10550,40.91144,-73.83804,146820.0,136672.0,140678.0,154313.0,1.487070e+05,1.454990e+05,151949
6,JPMorgan Chase Bank,0,Castle Hill Branch,12,12/11/1965,NaN,784 Castle Hill Avenue,Bronx,Bronx,NY,10473,40.82292,-73.84887,75131.0,80172.0,82333.0,94538.0,9.704600e+04,1.071660e+05,110592
7,JPMorgan Chase Bank,0,Burnside Avenue Branch,15,02/14/1922,NaN,5 West Burnside Avenue,Bronx,Bronx,NY,10453,40.85389,-73.90760,39888.0,42546.0,43800.0,45867.0,5.136300e+04,5.669300e+04,62993
8,JPMorgan Chase Bank,0,Gun Hill Branch,16,12/18/1950,NaN,1308 East Gun Hill Road,Bronx,Bronx,NY,10469,40.87151,-73.84823,73702.0,70049.0,70447.0,78946.0,8.067700e+04,8.275600e+04,88954
9,JPMorgan Chase Bank,0,Kingsbridge Road Branch,18,08/18/1924,NaN,66 East Kingsbridge Road,Bronx,Bronx,NY,10468,40.86671,-73.89562,69778.0,72816.0,74729.0,75470.0,7.875900e+04,8.397800e+04,88674
10,JPMorgan Chase Bank,0,Riverdale Branch,20,06/01/1950,NaN,3775 Riverdale Avenue,Bronx,Bronx,NY,10463,40.88763,-73.90737,304300.0,311508.0,330224.0,360791.0,3.672020e+05,3.644350e+05,387333
11,JPMorgan Chase Bank,0,Washington Heights Branch,21,01/02/1909,NaN,1421 Saint Nicholas Avenue,New York City,New York,NY,10033,40.84941,-73.93370,136997.0,142882.0,151420.0,158669.0,1.578620e+05,1.633360e+05,179566
12,JPMorgan Chase Bank,0,Broadway Branch,22,07/12/1926,NaN,5581 Broadway,Bronx,Bronx,NY,10463,40.87913,-73.90465,113665.0,112165.0,122634.0,126619.0,1.240310e+05,1.344750e+05,131545
13,JPMorgan Chase Bank,0,Westchester Square Branch,24,06/29/1959,NaN,2725 East Tremont Avenue,Bronx,Bronx,NY,10461,40.84239,-73.84501,155289.0,157396.0,161177.0,169839.0,1.674950e+05,1.835440e+05,194609
14,JPMorgan Chase Bank,0,Bay Parkway and 85th St Branch,26,03/25/1964,NaN,8418 Bay Parkway,Brooklyn,Kings,NY,11214,40.60268,-73.99304,187794.0,195965.0,214398.0,227519.0,2.521240e+05,2.785470e+05,297821
15,JPMorgan Chase Bank,0,Grand Army Plaza Branch,33,03/14/1927,NaN,401 Flatbush Avenue,Brooklyn,Kings,NY,11238,40.67576,-73.97135,135506.0,136764.0,146051.0,163797.0,1.780010e+05,2.276470e+05,255084
16,JPMorgan Chase Bank,0,Carroll Gardens Branch,34,06/09/1913,NaN,79 Hamilton Avenue,Brooklyn,Kings,NY,11231,40.68279,-74.00556,46199.0,51254.0,54859.0,70898.0,6.982400e+04,7.753600e+04,79441
17,JPMorgan Chase Bank,0,Third Avenue & 51st Street Branch,37,05/05/1961,NaN,850 Third Avenue,New York City,New York,NY,10022,40.75675,-73.97008,463550.0,456859.0,508804.0,540179.0,5.957860e+05,5.817250e+05,643283
18,JPMorgan Chase Bank,0,East End Branch,38,05/22/1961,NaN,1495 York Avenue,New York City,New York,NY,10075,40.77158,-73.95038,299301.0,306225.0,317068.0,359173.0,4.107370e+05,4.251690e+05,447613
19,JPMorgan Chase Bank,0,Audubon Branch,40,04/02/1917,NaN,3940 Broadway,New York City,New York,NY,10032,40.83951,-73.94077,91380.0,97219.0,104093.0,106875.0,1.142920e+05,1.222200e+05,139830
20,JPMorgan Chase Bank,0,First Avenue & 72nd Street Branch,41,06/15/1964,NaN,360 East 72nd Street,New York City,New York,NY,10021,40.76815,-73.95696,384454.0,364852.0,387515.0,440753.0,5.005740e+05,4.838350e+05,536219
21,JPMorgan Chase Bank,0,Soho Branch,42,10/18/1954,NaN,525 Broadway,New York City,New York,NY,10012,40.72290,-73.99889,286082.0,320252.0,344141.0,385854.0,4.888860e+05,5.081220e+05,615029
22,JPMorgan Chase Bank,0,Times Square Branch,44,05/02/1927,NaN,3 Times Square,New York City,New York,NY,10036,40.75658,-73.98629,313024.0,338725.0,432032.0,449569.0,4.740470e+05,4.959290e+05,532606
23,JPMorgan Chase Bank,0,Broadway Lispenard Branch,45,08/01/1922,NaN,407 Broadway,New York City,New York,NY,10013,40.72258,-74.00624,150592.0,160595.0,204645.0,244811.0,2.757260e+05,3.069020e+05,333954
24,JPMorgan Chase Bank,0,Chinatown Branch,46,11/24/1919,NaN,180 Canal Street,New York City,New York,NY,10013,40.71668,-73.99770,480964.0,523824.0,589914.0,638030.0,7.156070e+05,7.914130e+05,892267
25,JPMorgan Chase Bank,0,Yorkville Branch,52,06/15/1914,NaN,126 East 86th Street,New York City,New York,NY,10028,40.77966,-73.95609,383871.0,410662.0,437302.0,490441.0,5.388600e+05,5.265580e+05,535283
26,JPMorgan Chase Bank,0,Columbus Avenue & 72nd Street Branch,62,10/18/1954,NaN,260 Columbus Avenue,New York City,New York,NY,10023,40.77746,-73.97885,311593.0,350759.0,338917.0,356374.0,3.843710e+05,3.830140e+05,429310
27,JPMorgan Chase Bank,0,Bloomingdales Branch,63,08/02/1915,NaN,770 Lexington Avenue,New York City,New York,NY,10065,40.76302,-73.96761,273852.0,284524.0,295659.0,301179.0,3.650230e+05,3.569220e+05,353925
28,JPMorgan Chase Bank,0,London Terrace Branch,64,05/01/1931,NaN,475 West 23rd Street,New York City,New York,NY,10011,40.74743,-74.00339,143289.0,163960.0,168332.0,194739.0,2.245360e+05,2.455730e+05,249426
29,JPMorgan Chase Bank,0,Tremont Branch,71,10/18/1954,NaN,601 East Tremont Avenue,Bronx,Bronx,NY,10457,40.84628,-73.89296,48180.0,43965.0,45267.0,48717.0,5.394900e+04,5.609300e+04,56539
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5383,JPMorgan Chase Bank,0,Polo Club Shoppes Branch,7952,06/02/2015,NaN,17955 South Military Trail,Boca Raton,Palm Beach,FL,33496,26.40962,-80.12185,NaN,NaN,NaN,NaN,NaN,1.470000e+03,19184
5384,JPMorgan Chase Bank,0,Brookhurst and Mcfadden Branch,7953,07/07/2015,NaN,15512 Brrokhurst Street,Westminster,Orange,CA,92683,33.73733,-117.95465,NaN,NaN,NaN,NaN,NaN,NaN,24401
5385,JPMorgan Chase Bank,0,US 1 and Pga Boulevard Branch,7955,07/15/2014,NaN,11364 US Highway 1,Palm Beach Gardens,Palm Beach,FL,33408,26.84179,-80.06188,NaN,NaN,NaN,NaN,NaN,6.159000e+03,15358
5386,JPMorgan Chase Bank,0,San Marco Branch,7956,09/03/2014,NaN,11364 US Highway 1,Jacksonville,Duval,FL,32219,30.44229,-81.76591,NaN,NaN,NaN,NaN,NaN,6.153000e+03,14266
5387,JPMorgan Chase Bank,0,Park and Greenbay Branch,7957,09/04/2014,NaN,332 Park Avenue,Glencoe,Cook,IL,60022,42.13445,-87.75890,NaN,NaN,NaN,NaN,NaN,8.045000e+03,15646
5388,JPMorgan Chase Bank,0,Bedford Hills Branch,7958,11/04/2014,NaN,711 Bedford Road,Bedford Hills,Westchester,NY,10507,41.22460,-73.71420,NaN,NaN,NaN,NaN,NaN,8.302000e+03,8848
5389,JPMorgan Chase Bank,0,Siesta and Tamiami Branch,7959,12/16/2014,NaN,3500 South Tamiami Trail,Sarasota,Sarasota,FL,34239,27.30253,-82.53040,NaN,NaN,NaN,NaN,NaN,6.474000e+03,15235
5390,JPMorgan Chase Bank,0,Gellert and Westborough Branch,7960,01/27/2015,NaN,"2248 Westborough Boulevard, Suite 601 and 602",South San Francisco,San Mateo,CA,94080,37.65573,-122.42804,NaN,NaN,NaN,NaN,NaN,5.406000e+03,15856
5391,JPMorgan Chase Bank,0,Federal Highway and 5th Avenue Branch,7961,02/10/2015,NaN,1850 North Federal Highway,Boca Raton,Palm Beach,FL,33432,26.36682,-80.07848,NaN,NaN,NaN,NaN,NaN,1.742000e+03,7331
5392,JPMorgan Chase Bank,0,Norwalk Waypointe Branch,7962,04/14/2015,NaN,515 West Avenue,Norwalk,Fairfield,CT,6850,41.11189,-73.41648,NaN,NaN,NaN,NaN,NaN,3.990000e+02,3888
5393,JPMorgan Chase Bank,0,Fleming Island Cr 220 Branch,7963,04/21/2015,NaN,1516 Cr 220,Fleming Island,Clay,FL,32003,30.10245,-81.70911,NaN,NaN,NaN,NaN,NaN,2.914000e+03,10912
5394,JPMorgan Chase Bank,0,Manatee and 75th Branch,7964,04/23/2015,NaN,7206 Manatee Avenue West,Bradenton,Manatee,FL,34209,27.49612,-82.63335,NaN,NaN,NaN,NaN,NaN,1.046600e+04,20377
5395,JPMorgan Chase Bank,0,Camino Alto & East Blithdale Banking Center,7965,07/21/2015,NaN,630 East Blithedale Ave,Mill Valley,Marin,CA,94941,37.90032,-122.52838,NaN,NaN,NaN,NaN,NaN,NaN,18398
5396,JPMorgan Chase Bank,0,North Flemington Branch,7967,07/21/2015,NaN,318 State Route 31,Flemington,Hunterdon,NJ,8822,40.53951,-74.85741,NaN,NaN,NaN,NaN,NaN,NaN,7399
5397,JPMorgan Chase Bank,0,Village Of Merrick Park Branch,7969,09/28/2015,NaN,4101 Ponce De Leon Blvd,Coral Gables,Miami-Dade,FL,33146,25.73373,-80.25846,NaN,NaN,NaN,NaN,NaN,NaN,90046
5398,JPMorgan Chase Bank,0,Forest Hill Blvd and 441,7970,10/13/2015,NaN,10100 Forest Hill Blvd,Wellington,Palm Beach,FL,33414,26.65059,-80.20469,NaN,NaN,NaN,NaN,NaN,NaN,8135
5399,JPMorgan Chase Bank,0,Easter and University Branch,7971,10/26/2015,NaN,6900 South University Blvd,Centennial,Arapahoe,CO,80122,39.59193,-104.96018,NaN,NaN,NaN,NaN,NaN,NaN,55675
5400,JPMorgan Chase Bank,0,Hamilton and Jefferson Branch,7972,10/26/2015,NaN,125 Ne Jefferson Avenue,Peoria,Peoria,IL,61602,40.69306,-89.59027,NaN,NaN,NaN,NaN,NaN,NaN,170769
5401,JPMorgan Chase Bank,0,Coconut Grove Branch,7973,11/10/2015,NaN,3015 Grand Avenue,Miami,Miami-Dade,FL,33133,25.72817,-80.24199,NaN,NaN,NaN,NaN,NaN,NaN,6634
5402,JPMorgan Chase Bank,0,Park Place Branch,7974,11/17/2015,NaN,"2967 Michelson Drive, Suite A",Irvine,Orange,CA,92612,33.67125,-117.84538,NaN,NaN,NaN,NaN,NaN,NaN,11600
5403,JPMorgan Chase Bank,0,LA Paz Road and Aliso Creek Branch,7975,12/03/2015,NaN,23970 Aliso Creek Road,Laguna Niguel,Orange,CA,92677,33.55544,-117.71183,NaN,NaN,NaN,NaN,NaN,NaN,4809
5404,JPMorgan Chase Bank,0,Oklahoma City Downtown Branch,7976,12/07/2015,NaN,320 North Broadway Avenue,Oklahoma City,Oklahoma,OK,73102,35.47050,-97.51438,NaN,NaN,NaN,NaN,NaN,NaN,2551581
5405,JPMorgan Chase Bank,0,Tampa Downtown Branch,7978,04/26/2016,NaN,300 North Franklin Street,Tampa,Hillsborough,FL,33602,27.94710,-82.45770,NaN,NaN,NaN,NaN,NaN,NaN,684
5406,JPMorgan Chase Bank,0,Bartram Park and Old St. Augustine Branch,7979,05/10/2016,NaN,"13920 Old St. Augustine Road, Unit 107",Jacksonville,Duval,FL,32258,30.14180,-81.54606,NaN,NaN,NaN,NaN,NaN,NaN,2271
5407,JPMorgan Chase Bank,0,Desoto and Ventura Branch,7980,05/24/2016,NaN,20900 Ventura Blvd,Woodland Hills,Los Angeles,CA,91364,34.16641,-118.58866,NaN,NaN,NaN,NaN,NaN,NaN,2571
5408,JPMorgan Chase Bank,0,Alameda and Compton Blvd Branch,7981,11/03/2015,NaN,251 E Compton Blvd,Compton,Los Angeles,CA,90220,33.89601,-118.22084,NaN,NaN,NaN,NaN,NaN,NaN,3446
5409,JPMorgan Chase Bank,0,Charleston and Rancho,7982,02/02/2016,NaN,2311 W Chafrleston Blvd,Las Vegas,Clark,NV,89102,36.14270,-115.19043,NaN,NaN,NaN,NaN,NaN,NaN,2666
5410,JPMorgan Chase Bank,0,Los Olivos Branch,7984,03/15/2016,NaN,8593 Irvine Center Drive,Irvine,Orange,CA,92618,33.64412,-117.74453,NaN,NaN,NaN,NaN,NaN,NaN,6689
5411,JPMorgan Chase Bank,0,Lake Forest Branch,7988,01/01/2016,NaN,5660 Read Blvd,New Orleans,Orleans,LA,70127,30.03205,-89.97260,NaN,NaN,NaN,NaN,NaN,NaN,94133
5412,JPMorgan Chase Bank,0,Buffalo-Mm Branch,7989,01/01/2016,NaN,350 Main Street,Buffalo,Erie,NY,14202,42.88429,-78.87487,NaN,NaN,NaN,NaN,NaN,NaN,45596